version: "3.0"

services:
  scanner:
    volumes:
      - .:/master/scanner
    working_dir: /master/scanner
    env_file:
      - .env
#    command: bash -c "
#      gunicorn main_fastapi_ws:app
#      -w ${WEBSOCKET_NUM_WORKERS}
#      -k uvicorn.workers.UvicornWorker
#      --bind ${WEBSOCKET_HOST}:${WEBSOCKET_PORT}
#      --log-level ${WEBSOCKET_LOG_LEVEL}
#      --access-logfile ${WEBSOCKET_LOG_FILE}
#      "
    stdin_open: true
    tty: true
